-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.2 (win64) Build 2258646 Thu Jun 14 20:03:12 MDT 2018
-- Date        : Thu Jul 29 21:00:51 2021
-- Host        : LAPTOP-NGD1H6KK running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_YOLO2_FPGA_0_0_stub.vhdl
-- Design      : design_1_YOLO2_FPGA_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_CTRL_BUS_AWADDR : in STD_LOGIC_VECTOR ( 8 downto 0 );
    s_axi_CTRL_BUS_AWVALID : in STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : out STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_CTRL_BUS_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_CTRL_BUS_WVALID : in STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : out STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_CTRL_BUS_BVALID : out STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : in STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : in STD_LOGIC_VECTOR ( 8 downto 0 );
    s_axi_CTRL_BUS_ARVALID : in STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : out STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_CTRL_BUS_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_CTRL_BUS_RVALID : out STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_DATA_BUS1_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS1_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS1_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS1_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS1_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS1_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS1_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS1_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS1_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS1_AWVALID : out STD_LOGIC;
    m_axi_DATA_BUS1_AWREADY : in STD_LOGIC;
    m_axi_DATA_BUS1_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS1_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS1_WLAST : out STD_LOGIC;
    m_axi_DATA_BUS1_WVALID : out STD_LOGIC;
    m_axi_DATA_BUS1_WREADY : in STD_LOGIC;
    m_axi_DATA_BUS1_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS1_BVALID : in STD_LOGIC;
    m_axi_DATA_BUS1_BREADY : out STD_LOGIC;
    m_axi_DATA_BUS1_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS1_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS1_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS1_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS1_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS1_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS1_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS1_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS1_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS1_ARVALID : out STD_LOGIC;
    m_axi_DATA_BUS1_ARREADY : in STD_LOGIC;
    m_axi_DATA_BUS1_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS1_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS1_RLAST : in STD_LOGIC;
    m_axi_DATA_BUS1_RVALID : in STD_LOGIC;
    m_axi_DATA_BUS1_RREADY : out STD_LOGIC;
    m_axi_DATA_BUS2_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS2_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS2_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS2_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS2_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS2_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS2_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS2_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS2_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS2_AWVALID : out STD_LOGIC;
    m_axi_DATA_BUS2_AWREADY : in STD_LOGIC;
    m_axi_DATA_BUS2_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS2_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS2_WLAST : out STD_LOGIC;
    m_axi_DATA_BUS2_WVALID : out STD_LOGIC;
    m_axi_DATA_BUS2_WREADY : in STD_LOGIC;
    m_axi_DATA_BUS2_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS2_BVALID : in STD_LOGIC;
    m_axi_DATA_BUS2_BREADY : out STD_LOGIC;
    m_axi_DATA_BUS2_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS2_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS2_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS2_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS2_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS2_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS2_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS2_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS2_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS2_ARVALID : out STD_LOGIC;
    m_axi_DATA_BUS2_ARREADY : in STD_LOGIC;
    m_axi_DATA_BUS2_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS2_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS2_RLAST : in STD_LOGIC;
    m_axi_DATA_BUS2_RVALID : in STD_LOGIC;
    m_axi_DATA_BUS2_RREADY : out STD_LOGIC;
    m_axi_DATA_BUS3_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS3_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS3_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS3_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS3_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS3_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS3_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS3_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS3_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS3_AWVALID : out STD_LOGIC;
    m_axi_DATA_BUS3_AWREADY : in STD_LOGIC;
    m_axi_DATA_BUS3_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS3_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS3_WLAST : out STD_LOGIC;
    m_axi_DATA_BUS3_WVALID : out STD_LOGIC;
    m_axi_DATA_BUS3_WREADY : in STD_LOGIC;
    m_axi_DATA_BUS3_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS3_BVALID : in STD_LOGIC;
    m_axi_DATA_BUS3_BREADY : out STD_LOGIC;
    m_axi_DATA_BUS3_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS3_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS3_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS3_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS3_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS3_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS3_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS3_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS3_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS3_ARVALID : out STD_LOGIC;
    m_axi_DATA_BUS3_ARREADY : in STD_LOGIC;
    m_axi_DATA_BUS3_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS3_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS3_RLAST : in STD_LOGIC;
    m_axi_DATA_BUS3_RVALID : in STD_LOGIC;
    m_axi_DATA_BUS3_RREADY : out STD_LOGIC;
    m_axi_DATA_BUS4_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS4_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS4_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS4_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS4_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS4_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS4_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS4_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS4_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS4_AWVALID : out STD_LOGIC;
    m_axi_DATA_BUS4_AWREADY : in STD_LOGIC;
    m_axi_DATA_BUS4_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS4_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS4_WLAST : out STD_LOGIC;
    m_axi_DATA_BUS4_WVALID : out STD_LOGIC;
    m_axi_DATA_BUS4_WREADY : in STD_LOGIC;
    m_axi_DATA_BUS4_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS4_BVALID : in STD_LOGIC;
    m_axi_DATA_BUS4_BREADY : out STD_LOGIC;
    m_axi_DATA_BUS4_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS4_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS4_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS4_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS4_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS4_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS4_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS4_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS4_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS4_ARVALID : out STD_LOGIC;
    m_axi_DATA_BUS4_ARREADY : in STD_LOGIC;
    m_axi_DATA_BUS4_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS4_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS4_RLAST : in STD_LOGIC;
    m_axi_DATA_BUS4_RVALID : in STD_LOGIC;
    m_axi_DATA_BUS4_RREADY : out STD_LOGIC;
    m_axi_DATA_BUS5_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS5_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS5_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS5_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS5_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS5_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS5_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS5_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS5_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS5_AWVALID : out STD_LOGIC;
    m_axi_DATA_BUS5_AWREADY : in STD_LOGIC;
    m_axi_DATA_BUS5_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS5_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS5_WLAST : out STD_LOGIC;
    m_axi_DATA_BUS5_WVALID : out STD_LOGIC;
    m_axi_DATA_BUS5_WREADY : in STD_LOGIC;
    m_axi_DATA_BUS5_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS5_BVALID : in STD_LOGIC;
    m_axi_DATA_BUS5_BREADY : out STD_LOGIC;
    m_axi_DATA_BUS5_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS5_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_DATA_BUS5_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS5_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS5_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS5_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS5_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS5_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_DATA_BUS5_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_DATA_BUS5_ARVALID : out STD_LOGIC;
    m_axi_DATA_BUS5_ARREADY : in STD_LOGIC;
    m_axi_DATA_BUS5_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_DATA_BUS5_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_DATA_BUS5_RLAST : in STD_LOGIC;
    m_axi_DATA_BUS5_RVALID : in STD_LOGIC;
    m_axi_DATA_BUS5_RREADY : out STD_LOGIC
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "s_axi_CTRL_BUS_AWADDR[8:0],s_axi_CTRL_BUS_AWVALID,s_axi_CTRL_BUS_AWREADY,s_axi_CTRL_BUS_WDATA[31:0],s_axi_CTRL_BUS_WSTRB[3:0],s_axi_CTRL_BUS_WVALID,s_axi_CTRL_BUS_WREADY,s_axi_CTRL_BUS_BRESP[1:0],s_axi_CTRL_BUS_BVALID,s_axi_CTRL_BUS_BREADY,s_axi_CTRL_BUS_ARADDR[8:0],s_axi_CTRL_BUS_ARVALID,s_axi_CTRL_BUS_ARREADY,s_axi_CTRL_BUS_RDATA[31:0],s_axi_CTRL_BUS_RRESP[1:0],s_axi_CTRL_BUS_RVALID,s_axi_CTRL_BUS_RREADY,ap_clk,ap_rst_n,interrupt,m_axi_DATA_BUS1_AWADDR[31:0],m_axi_DATA_BUS1_AWLEN[7:0],m_axi_DATA_BUS1_AWSIZE[2:0],m_axi_DATA_BUS1_AWBURST[1:0],m_axi_DATA_BUS1_AWLOCK[1:0],m_axi_DATA_BUS1_AWREGION[3:0],m_axi_DATA_BUS1_AWCACHE[3:0],m_axi_DATA_BUS1_AWPROT[2:0],m_axi_DATA_BUS1_AWQOS[3:0],m_axi_DATA_BUS1_AWVALID,m_axi_DATA_BUS1_AWREADY,m_axi_DATA_BUS1_WDATA[31:0],m_axi_DATA_BUS1_WSTRB[3:0],m_axi_DATA_BUS1_WLAST,m_axi_DATA_BUS1_WVALID,m_axi_DATA_BUS1_WREADY,m_axi_DATA_BUS1_BRESP[1:0],m_axi_DATA_BUS1_BVALID,m_axi_DATA_BUS1_BREADY,m_axi_DATA_BUS1_ARADDR[31:0],m_axi_DATA_BUS1_ARLEN[7:0],m_axi_DATA_BUS1_ARSIZE[2:0],m_axi_DATA_BUS1_ARBURST[1:0],m_axi_DATA_BUS1_ARLOCK[1:0],m_axi_DATA_BUS1_ARREGION[3:0],m_axi_DATA_BUS1_ARCACHE[3:0],m_axi_DATA_BUS1_ARPROT[2:0],m_axi_DATA_BUS1_ARQOS[3:0],m_axi_DATA_BUS1_ARVALID,m_axi_DATA_BUS1_ARREADY,m_axi_DATA_BUS1_RDATA[31:0],m_axi_DATA_BUS1_RRESP[1:0],m_axi_DATA_BUS1_RLAST,m_axi_DATA_BUS1_RVALID,m_axi_DATA_BUS1_RREADY,m_axi_DATA_BUS2_AWADDR[31:0],m_axi_DATA_BUS2_AWLEN[7:0],m_axi_DATA_BUS2_AWSIZE[2:0],m_axi_DATA_BUS2_AWBURST[1:0],m_axi_DATA_BUS2_AWLOCK[1:0],m_axi_DATA_BUS2_AWREGION[3:0],m_axi_DATA_BUS2_AWCACHE[3:0],m_axi_DATA_BUS2_AWPROT[2:0],m_axi_DATA_BUS2_AWQOS[3:0],m_axi_DATA_BUS2_AWVALID,m_axi_DATA_BUS2_AWREADY,m_axi_DATA_BUS2_WDATA[31:0],m_axi_DATA_BUS2_WSTRB[3:0],m_axi_DATA_BUS2_WLAST,m_axi_DATA_BUS2_WVALID,m_axi_DATA_BUS2_WREADY,m_axi_DATA_BUS2_BRESP[1:0],m_axi_DATA_BUS2_BVALID,m_axi_DATA_BUS2_BREADY,m_axi_DATA_BUS2_ARADDR[31:0],m_axi_DATA_BUS2_ARLEN[7:0],m_axi_DATA_BUS2_ARSIZE[2:0],m_axi_DATA_BUS2_ARBURST[1:0],m_axi_DATA_BUS2_ARLOCK[1:0],m_axi_DATA_BUS2_ARREGION[3:0],m_axi_DATA_BUS2_ARCACHE[3:0],m_axi_DATA_BUS2_ARPROT[2:0],m_axi_DATA_BUS2_ARQOS[3:0],m_axi_DATA_BUS2_ARVALID,m_axi_DATA_BUS2_ARREADY,m_axi_DATA_BUS2_RDATA[31:0],m_axi_DATA_BUS2_RRESP[1:0],m_axi_DATA_BUS2_RLAST,m_axi_DATA_BUS2_RVALID,m_axi_DATA_BUS2_RREADY,m_axi_DATA_BUS3_AWADDR[31:0],m_axi_DATA_BUS3_AWLEN[7:0],m_axi_DATA_BUS3_AWSIZE[2:0],m_axi_DATA_BUS3_AWBURST[1:0],m_axi_DATA_BUS3_AWLOCK[1:0],m_axi_DATA_BUS3_AWREGION[3:0],m_axi_DATA_BUS3_AWCACHE[3:0],m_axi_DATA_BUS3_AWPROT[2:0],m_axi_DATA_BUS3_AWQOS[3:0],m_axi_DATA_BUS3_AWVALID,m_axi_DATA_BUS3_AWREADY,m_axi_DATA_BUS3_WDATA[31:0],m_axi_DATA_BUS3_WSTRB[3:0],m_axi_DATA_BUS3_WLAST,m_axi_DATA_BUS3_WVALID,m_axi_DATA_BUS3_WREADY,m_axi_DATA_BUS3_BRESP[1:0],m_axi_DATA_BUS3_BVALID,m_axi_DATA_BUS3_BREADY,m_axi_DATA_BUS3_ARADDR[31:0],m_axi_DATA_BUS3_ARLEN[7:0],m_axi_DATA_BUS3_ARSIZE[2:0],m_axi_DATA_BUS3_ARBURST[1:0],m_axi_DATA_BUS3_ARLOCK[1:0],m_axi_DATA_BUS3_ARREGION[3:0],m_axi_DATA_BUS3_ARCACHE[3:0],m_axi_DATA_BUS3_ARPROT[2:0],m_axi_DATA_BUS3_ARQOS[3:0],m_axi_DATA_BUS3_ARVALID,m_axi_DATA_BUS3_ARREADY,m_axi_DATA_BUS3_RDATA[31:0],m_axi_DATA_BUS3_RRESP[1:0],m_axi_DATA_BUS3_RLAST,m_axi_DATA_BUS3_RVALID,m_axi_DATA_BUS3_RREADY,m_axi_DATA_BUS4_AWADDR[31:0],m_axi_DATA_BUS4_AWLEN[7:0],m_axi_DATA_BUS4_AWSIZE[2:0],m_axi_DATA_BUS4_AWBURST[1:0],m_axi_DATA_BUS4_AWLOCK[1:0],m_axi_DATA_BUS4_AWREGION[3:0],m_axi_DATA_BUS4_AWCACHE[3:0],m_axi_DATA_BUS4_AWPROT[2:0],m_axi_DATA_BUS4_AWQOS[3:0],m_axi_DATA_BUS4_AWVALID,m_axi_DATA_BUS4_AWREADY,m_axi_DATA_BUS4_WDATA[31:0],m_axi_DATA_BUS4_WSTRB[3:0],m_axi_DATA_BUS4_WLAST,m_axi_DATA_BUS4_WVALID,m_axi_DATA_BUS4_WREADY,m_axi_DATA_BUS4_BRESP[1:0],m_axi_DATA_BUS4_BVALID,m_axi_DATA_BUS4_BREADY,m_axi_DATA_BUS4_ARADDR[31:0],m_axi_DATA_BUS4_ARLEN[7:0],m_axi_DATA_BUS4_ARSIZE[2:0],m_axi_DATA_BUS4_ARBURST[1:0],m_axi_DATA_BUS4_ARLOCK[1:0],m_axi_DATA_BUS4_ARREGION[3:0],m_axi_DATA_BUS4_ARCACHE[3:0],m_axi_DATA_BUS4_ARPROT[2:0],m_axi_DATA_BUS4_ARQOS[3:0],m_axi_DATA_BUS4_ARVALID,m_axi_DATA_BUS4_ARREADY,m_axi_DATA_BUS4_RDATA[31:0],m_axi_DATA_BUS4_RRESP[1:0],m_axi_DATA_BUS4_RLAST,m_axi_DATA_BUS4_RVALID,m_axi_DATA_BUS4_RREADY,m_axi_DATA_BUS5_AWADDR[31:0],m_axi_DATA_BUS5_AWLEN[7:0],m_axi_DATA_BUS5_AWSIZE[2:0],m_axi_DATA_BUS5_AWBURST[1:0],m_axi_DATA_BUS5_AWLOCK[1:0],m_axi_DATA_BUS5_AWREGION[3:0],m_axi_DATA_BUS5_AWCACHE[3:0],m_axi_DATA_BUS5_AWPROT[2:0],m_axi_DATA_BUS5_AWQOS[3:0],m_axi_DATA_BUS5_AWVALID,m_axi_DATA_BUS5_AWREADY,m_axi_DATA_BUS5_WDATA[31:0],m_axi_DATA_BUS5_WSTRB[3:0],m_axi_DATA_BUS5_WLAST,m_axi_DATA_BUS5_WVALID,m_axi_DATA_BUS5_WREADY,m_axi_DATA_BUS5_BRESP[1:0],m_axi_DATA_BUS5_BVALID,m_axi_DATA_BUS5_BREADY,m_axi_DATA_BUS5_ARADDR[31:0],m_axi_DATA_BUS5_ARLEN[7:0],m_axi_DATA_BUS5_ARSIZE[2:0],m_axi_DATA_BUS5_ARBURST[1:0],m_axi_DATA_BUS5_ARLOCK[1:0],m_axi_DATA_BUS5_ARREGION[3:0],m_axi_DATA_BUS5_ARCACHE[3:0],m_axi_DATA_BUS5_ARPROT[2:0],m_axi_DATA_BUS5_ARQOS[3:0],m_axi_DATA_BUS5_ARVALID,m_axi_DATA_BUS5_ARREADY,m_axi_DATA_BUS5_RDATA[31:0],m_axi_DATA_BUS5_RRESP[1:0],m_axi_DATA_BUS5_RLAST,m_axi_DATA_BUS5_RVALID,m_axi_DATA_BUS5_RREADY";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "YOLO2_FPGA,Vivado 2018.2";
begin
end;
